services:
  - type: web
    name: erasebg-backend
    runtime: python
    rootDir: render-app
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: FRONTEND_URL
        value: https://erasebg-frontend.vercel.app
      - key: LOG_LEVEL
        value: INFO
      - key: PRELOAD_MODELS_ON_STARTUP
        value: "false"
      - key: WARMUP_ON_STARTUP
        value: "false"
    plan: free
